/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite build
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// API routes — NetworkFirst, NO caching (admin data must be fresh)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-runtime',
    networkTimeoutSeconds: 5,
  }),
);

// Google Fonts — CacheFirst (static assets)
registerRoute(
  ({ url }) => /fonts\.googleapis\.com|fonts\.gstatic\.com/.test(url.origin),
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [
      new CacheableResponsePlugin({ statuses: [0, 200] }),
      new ExpirationPlugin({ maxEntries: 30, maxAgeSeconds: 30 * 24 * 60 * 60 }),
    ],
  }),
);

// SPA navigate fallback
const navigateFallback = '/index.html';
self.addEventListener('fetch', (event) => {
  if (
    event.request.mode === 'navigate' &&
    !event.request.url.startsWith(self.location.origin + '/api/')
  ) {
    event.respondWith(
      fetch(event.request).catch(() => caches.match(navigateFallback) as Promise<Response>),
    );
  }
});

// Activate — claim clients immediately
self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Push event — admin notifications
self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();

    event.waitUntil(
      self.clients.matchAll({ type: 'window' }).then((clients) => {
        if (clients.length > 0) return; // App open → in-app toast handles it

        return self.registration.showNotification(data.title, {
          body: data.message,
          icon: '/icons/pwa-192x192.png',
          badge: '/icons/badge-72x72.png',
          vibrate: [200, 100, 200],
          data: {
            url: data.data?.url || '/',
            event: data.event,
          },
          tag: `${data.event}:${Date.now()}`,
          renotify: true,
          actions: [
            { action: 'open', title: 'Ver' },
            { action: 'close', title: 'Cerrar' },
          ],
        } as NotificationOptions);
      }),
    );
  } catch (err) {
    console.error('[SW] push error:', err);
  }
});

// Notification click — open/focus admin page
self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  if (event.action === 'close') return;

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      const existing = windowClients.find((c) => c.url === urlToOpen);
      if (existing) return existing.focus();
      if (windowClients.length > 0) {
        return windowClients[0].navigate(urlToOpen).then((c) => c?.focus());
      }
      return self.clients.openWindow(urlToOpen);
    }),
  );
});

// Message handler — SKIP_WAITING for updates
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
