/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst, CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';

declare const self: ServiceWorkerGlobalScope;

// Precache all assets generated by Vite build
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// Runtime caching (same as previous generateSW config)
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/recipes'),
  new StaleWhileRevalidate({
    cacheName: 'recipes-cache',
    plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })],
  }),
);

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  new NetworkFirst({
    cacheName: 'api-runtime',
    networkTimeoutSeconds: 5,
    plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })],
  }),
);

registerRoute(
  ({ url }) => /fonts\.googleapis\.com|fonts\.gstatic\.com/.test(url.origin),
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })],
  }),
);

registerRoute(
  ({ url }) => url.hostname.includes('images.unsplash.com'),
  new CacheFirst({
    cacheName: 'unsplash-images',
    plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })],
  }),
);

// Navigate fallback
const navigateFallback = '/index.html';
self.addEventListener('fetch', (event) => {
  if (
    event.request.mode === 'navigate' &&
    !event.request.url.startsWith(self.location.origin + '/api/')
  ) {
    event.respondWith(
      fetch(event.request).catch(() => caches.match(navigateFallback) as Promise<Response>),
    );
  }
});

// Skip waiting on install (preserves update prompt flow via registerType: 'prompt')
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Push event — receive push notification
self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();

    // Don't show native notification if app has open clients
    // (Socket.IO handles in-app toasts when app is open)
    event.waitUntil(
      self.clients.matchAll({ type: 'window' }).then((clients) => {
        if (clients.length > 0) return; // App is open, skip native notification

        return self.registration.showNotification(data.title, {
          body: data.message,
          icon: '/icons/pwa-192x192.png',
          badge: '/icons/badge-72x72.png',
          vibrate: [200, 100, 200],
          data: {
            url: data.data?.url || '/',
            event: data.event,
          },
          tag: `${data.event}:${Date.now()}`,
          renotify: true,
          actions: [
            { action: 'open', title: 'Abrir' },
            { action: 'close', title: 'Cerrar' },
          ],
        } as NotificationOptions);
      }),
    );
  } catch (err) {
    console.error('[SW] push event error:', err);
  }
});

// Notification click — open/focus window with correct URL
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  if (event.action === 'close') return;

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients
      .matchAll({ type: 'window', includeUncontrolled: true })
      .then((windowClients) => {
        // Check if we already have a window with this URL
        const existing = windowClients.find((c) => c.url === urlToOpen);
        if (existing) {
          return existing.focus();
        }
        // Check if we have any window at all
        if (windowClients.length > 0) {
          return windowClients[0].navigate(urlToOpen).then((c) => c?.focus());
        }
        return self.clients.openWindow(urlToOpen);
      }),
  );
});
