/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, NetworkFirst, CacheFirst } from 'workbox-strategies';
import { CacheableResponsePlugin } from 'workbox-cacheable-response';
import { ExpirationPlugin } from 'workbox-expiration';

declare const self: ServiceWorkerGlobalScope;

let offlineEnabled = true;

// Precache all assets generated by Vite build
cleanupOutdatedCaches();
precacheAndRoute(self.__WB_MANIFEST);

// Recipe detail — CacheFirst so full recipe (steps, ingredients) works offline
const isRecipeDetail = (pathname: string) =>
  /^\/api\/recipes\/[\w-]+$/.test(pathname) || /^\/api\/recipes\/by-slug\/[\w-]+$/.test(pathname);

// Recipe list — SWR so new recipes appear without refresh
registerRoute(
  ({ url }) => url.pathname.startsWith('/api/recipes') && !isRecipeDetail(url.pathname),
  ({ request, event }) => {
    if (!offlineEnabled) {
      return new NetworkFirst({
        cacheName: 'api-runtime',
        networkTimeoutSeconds: 3,
      }).handle({ request, event });
    }
    return new StaleWhileRevalidate({
      cacheName: 'recipes-cache',
      plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })],
    }).handle({ request, event });
  },
);

registerRoute(
  ({ url }) => isRecipeDetail(url.pathname),
  ({ request, event }) => {
    if (!offlineEnabled) {
      return new NetworkFirst({
        cacheName: 'api-runtime',
        networkTimeoutSeconds: 3,
      }).handle({ request, event });
    }
    return new CacheFirst({
      cacheName: 'recipe-details',
      plugins: [
        new CacheableResponsePlugin({ statuses: [0, 200] }),
        new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 7 * 24 * 60 * 60 }),
      ],
    }).handle({ request, event });
  },
);

registerRoute(
  ({ url }) => url.pathname.startsWith('/api/'),
  ({ request, event }) => {
    if (!offlineEnabled) {
      return new NetworkFirst({
        cacheName: 'api-runtime',
        networkTimeoutSeconds: 3,
      }).handle({ request, event });
    }
    return new NetworkFirst({
      cacheName: 'api-runtime',
      networkTimeoutSeconds: 5,
      plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })],
    }).handle({ request, event });
  },
);

registerRoute(
  ({ url }) => /fonts\.googleapis\.com|fonts\.gstatic\.com/.test(url.origin),
  new CacheFirst({
    cacheName: 'google-fonts',
    plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })],
  }),
);

registerRoute(
  ({ url }) => url.hostname.includes('images.unsplash.com'),
  new CacheFirst({
    cacheName: 'unsplash-images',
    plugins: [new CacheableResponsePlugin({ statuses: [0, 200] })],
  }),
);

// Navigate fallback
const navigateFallback = '/index.html';
self.addEventListener('fetch', (event) => {
  if (
    event.request.mode === 'navigate' &&
    !event.request.url.startsWith(self.location.origin + '/api/')
  ) {
    event.respondWith(
      fetch(event.request).catch(() => caches.match(navigateFallback) as Promise<Response>),
    );
  }
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

// Push event — receive push notification
self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();

    // Don't show native notification if app has open clients
    // (Socket.IO handles in-app toasts when app is open)
    event.waitUntil(
      self.clients.matchAll({ type: 'window' }).then((clients) => {
        if (clients.length > 0) return; // App is open, skip native notification

        return self.registration.showNotification(data.title, {
          body: data.message,
          icon: '/icons/pwa-192x192.png',
          badge: '/icons/badge-72x72.png',
          vibrate: [200, 100, 200],
          data: {
            url: data.data?.url || '/',
            event: data.event,
          },
          tag: `${data.event}:${Date.now()}`,
          renotify: true,
          actions: [
            { action: 'open', title: 'Abrir' },
            { action: 'close', title: 'Cerrar' },
          ],
        } as NotificationOptions);
      }),
    );
  } catch (err) {
    console.error('[SW] push event error:', err);
  }
});

// Sync event — background sync for brew logs
self.addEventListener('sync', ((event: Event) => {
  const syncEvent = event as Event & { tag: string };
  if (syncEvent.tag === 'brew-sync') {
    const ext = event as ExtendableEvent;
    ext.waitUntil(
      self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((clients) => {
        for (const client of clients) {
          client.postMessage({ type: 'BREW_SYNC' });
        }
      }),
    );
  }
}) as EventListener);

// Notification click — open/focus window with correct URL
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  if (event.action === 'close') return;

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if we already have a window with this URL
      const existing = windowClients.find((c) => c.url === urlToOpen);
      if (existing) {
        return existing.focus();
      }
      // Check if we have any window at all
      if (windowClients.length > 0) {
        return windowClients[0].navigate(urlToOpen).then((c) => c?.focus());
      }
      return self.clients.openWindow(urlToOpen);
    }),
  );
});

// Message handler — required by workbox-window for SKIP_WAITING + offline mode toggle
self.addEventListener('message', (event) => {
  if (event.data?.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
  if (event.data?.type === 'OFFLINE_MODE_CHANGED') {
    offlineEnabled = event.data.enabled;
  }
});
